/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mk.itzone.kafkastreams.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RatedMovie2  {
  private static final long serialVersionUID = -7571293489741156781L;


   private long id;
   private java.lang.String title;
   private int releaseyear;
   private double rating;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RatedMovie2() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param title The new value for title
   * @param releaseyear The new value for releaseyear
   * @param rating The new value for rating
   */
  public RatedMovie2(java.lang.Long id, java.lang.String title, java.lang.Integer releaseyear, java.lang.Double rating) {
    this.id = id;
    this.title = title;
    this.releaseyear = releaseyear;
    this.rating = rating;
  }





  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }






  /**
   * Gets the value of the 'releaseyear' field.
   * @return The value of the 'releaseyear' field.
   */
  public int getReleaseyear() {
    return releaseyear;
  }



  /**
   * Gets the value of the 'rating' field.
   * @return The value of the 'rating' field.
   */
  public double getRating() {
    return rating;
  }









    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.String getTitle() {
      return title;
    }














}










